/* ============================================================
   Static-import registry for the parsed volumes.

   Static imports rather than fs reads, so the whole set is validated at build
   time by the bundler and works identically in a server component and a client
   component. An unknown slug is a 404 rather than a runtime surprise.

   This does not scale past a dozen or so entries and should be generated by
   then. At three it is still cheaper to read than a glob.
   ============================================================ */

import { ARCS, arcMeta } from './series';

import p1 from '@/content/volumes/p1.json';
import t1 from '@/content/volumes/t1.json';
import t2 from '@/content/volumes/t2.json';

const REGISTRY = { p1, t1, t2 };

/**
 * Volumes that are planned but not yet written.
 *
 * Listed here rather than omitted, so an arc shelf shows the shape of the
 * whole arc from the first day. A reader seeing "Prologue II — not yet
 * written" learns something true; an arc that silently grows from one tile to
 * three does not.
 */
export const PLANNED = [
  { slug: 'p2', arc: 'the-climb', order: 2, part: 'Prologue II', title: 'Not yet written' },
  { slug: 'p3', arc: 'the-climb', order: 3, part: 'Prologue III', title: 'Not yet written' },
];

export const VOLUME_SLUGS = Object.keys(REGISTRY);

/** Where a volume is read. Derived from its arc, never hardcoded at a call site. */
export const readHref = (slug) => {
  const arc = REGISTRY[slug]?.arc;
  return arc === 'tales' ? `/tales/${slug}/read` : `/climb/${slug}/read`;
};

/** Reading order WITHIN an arc, which is the only order that means anything. */
export const slugsForArc = (arcId) =>
  VOLUME_SLUGS
    .filter((s) => REGISTRY[s].arc === arcId)
    .sort((a, b) => REGISTRY[a].order - REGISTRY[b].order);

/**
 * One volume, shaped for the reader.
 *
 * Everything derived is derived here and never duplicated in the data: a
 * spread count stored in the JSON as well as computed from it is two sources
 * of truth for one number, with nothing checking they agree.
 */
export function loadVolume(slug) {
  const v = REGISTRY[slug];
  if (!v) return null;

  const story = v.spreads.filter((s) => s.kind === 'spread');
  const arc = arcMeta(v.arc);

  return {
    ...v,
    spreadCount: story.length,
    plateCount: v.spreads.length,
    words: story.reduce((a, s) => a + s.words, 0),
    // The jump list, built from the section headings inside the prose rather
    // than from a second hand-kept list that could drift out of agreement.
    sections: story.flatMap((s) =>
      (s.blocks || []).filter((b) => b.t === 'h').map((b) => ({ title: b.v, spread: s.n })),
    ),
    // Where the reader's back button goes: the section of the homepage the
    // reader came from, not the arc shelf. The homepage is the original static
    // site and is where every volume is entered from, so returning anywhere
    // else would strand someone in a part of the site they never visited.
    shelfHref: arc?.standalone ? '/#tales-section' : '/#chapters-section',
    shelfLabel: arc?.title || 'Back',
  };
}

export function volumesForArc(arcId) {
  const live = slugsForArc(arcId).map((s) => ({ ...loadVolume(s), status: 'live' }));
  const planned = PLANNED.filter((p) => p.arc === arcId).map((p) => ({ ...p, status: 'planned' }));
  return [...live, ...planned].sort((a, b) => a.order - b.order);
}

/**
 * Where a reader goes when they finish a volume.
 *
 * The NEXT VOLUME IN THE SAME ARC, or null at the end of it, which is the
 * caller's cue to offer the shelf instead. Scoped to the arc deliberately:
 * running off the end of The Climb into Tales would hand a reader a different
 * story with no indication they had left the one they were reading.
 */
export function nextVolume(slug) {
  const v = REGISTRY[slug];
  if (!v || arcMeta(v.arc)?.standalone) return null;

  const order = slugsForArc(v.arc);
  const i = order.indexOf(slug);
  if (i < 0 || i === order.length - 1) return null;

  const next = REGISTRY[order[i + 1]];
  return { slug: next.slug, href: readHref(next.slug), part: next.part, title: next.title };
}

export { ARCS, arcMeta };
