/* Build one drop-folder per plate: the prompt, and the exact images to attach.
   Millbrook shape — you open a folder, drag everything in it into the chat,
   paste the prompt, done. Nothing to look up and nothing to decide. */
const fs = require('fs');
const path = require('path');

// Which volume to package. `npm run package -- p3`, defaulting to the one
// most likely to be wanted rather than to a volume that is already finished.
const SLUG = process.argv[2] || 'p3';
const SHEET = path.join('prompt-sheets', SLUG + '.md');
const REFS = 'references';
const OUT = path.join('prompt-packages', SLUG);

const sheet = fs.readFileSync(SHEET, 'utf8');
const blocks = sheet.split(/^---$/m).slice(1);

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const plates = [];
for (const b of blocks) {
  const head = /^##\s+(.+?)\s+—\s+`(.+?)`/m.exec(b);
  if (!head) continue;
  const attach = [...b.matchAll(/^- `([^`]+)` — (.+)$/gm)].map((m) => ({ file: m[1], label: m[2] }));
  const code = /```\n([\s\S]*?)\n```/.exec(b);
  const field = (name) => {
    const m = new RegExp('\\*\\*' + name + ':?[^*]*\\*\\*\\s*(.+)').exec(b);
    return m ? m[1].trim() : '';
  };
  plates.push({
    leaf: head[1], slug: head[2], attach,
    prompt: code ? code[1] : '',
    shot: field('Shot'), caption: field('Caption'), depicts: field('Depicts'),
    spoiler: field('Spoiler check'), hard: field('Hard constraints'),
  });
}

const index = [];
plates.forEach((p, i) => {
  const n = String(i).padStart(2, '0');
  const dir = path.join(OUT, n + '-' + p.slug);
  fs.mkdirSync(dir, { recursive: true });

  const lines = [
    'CLIMBERS — ' + p.leaf + '  (' + p.slug + ')',
    '='.repeat(60), '',
    'ATTACH THE ' + p.attach.length + ' IMAGE(S) IN THIS FOLDER, THEN PASTE EVERYTHING BELOW THE LINE.',
    '',
  ];
  p.attach.forEach((a) => lines.push('  - ' + path.basename(a.file) + '   (' + a.label + ')'));
  lines.push('', 'Shot: ' + p.shot);
  if (p.caption) lines.push('Caption (not drawn — alt text only): ' + p.caption);
  if (p.spoiler) lines.push('Spoiler check: ' + p.spoiler);
  lines.push('', '-'.repeat(60), '', p.prompt, '');
  fs.writeFileSync(path.join(dir, 'PROMPT.txt'), lines.join('\r\n'));

  for (const a of p.attach) {
    const src = path.join(REFS, a.file);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(dir, path.basename(a.file)));
    else console.log('  MISSING ' + src);
  }
  index.push({ n, p, dir });
});

// ---- the single readable document ----
const md = [
  '# PROLOGUE I — THE ARCHITECT\'S ASCENT',
  '', '**' + plates.length + ' plates.** One folder per plate under `prompt-packages/p1/`.',
  'Each folder holds `PROMPT.txt` and the exact images to attach — drag the folder\'s',
  'images into ChatGPT, paste the prompt, generate.',
  '',
  'Generated by `npm run prompts` + the packager. Do not edit these by hand:',
  'edit `content/specs/p1.md` or `content/roster.json` and rebuild.',
  '',
  '## Palette rotation',
  '',
  '| # | Plate | Mode |',
  '|---|---|---|',
];
plates.forEach((p, i) => {
  const mode = (/PALETTE MODE: (PS-\d [A-Z ]+)/.exec(p.prompt) || [, '—'])[1].replace(/[,.]$/, '').trim();
  md.push('| ' + String(i).padStart(2, '0') + ' | ' + p.leaf + ' | ' + mode + ' |');
});
md.push('', '---', '');
plates.forEach((p, i) => {
  md.push('## ' + String(i).padStart(2, '0') + ' — ' + p.leaf + '  `' + p.slug + '`', '');
  md.push('**Folder:** `prompt-packages/p1/' + String(i).padStart(2, '0') + '-' + p.slug + '/`', '');
  md.push('**Attach:** ' + (p.attach.length ? p.attach.map((a) => '`' + path.basename(a.file) + '`').join(', ') : 'nothing'), '');
  if (p.depicts) md.push('**Depicts:** ' + p.depicts, '');
  if (p.hard) md.push('**Hard constraints:** ' + p.hard, '');
  if (p.spoiler) md.push('**Spoiler check:** ' + p.spoiler, '');
  md.push('```', p.prompt, '```', '');
});
fs.writeFileSync(path.join(OUT, 'ALL-PROMPTS.md'), md.join('\n'));

console.log(plates.length + ' packages built in ' + OUT);
console.log('attachments copied: ' + plates.reduce((a, p) => a + p.attach.length, 0));
